### ISSUE TITLE
[SDK] Not enough funds provides error on `squid.isRouteApproved`

### ISSUE THREAD

**Issue by ecdsafu** [0xsquid/squid-sdk#221]
## Description / Steps to reproduce

We don't allow to check for approval using the SDK function if the user doesn't have enough funds in their account. This seems incorrect, we should return true or false, even if they don't have enough funds.

```typescript
Error: Insufficient funds for account: 0x7dBd0F75aA91c757ae6564d41dd59669023D57a4 on chain 43114
    at EvmHandler.validateTokenBalance (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/handlers/evm/utils.ts:45:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EvmHandler.validateBalance (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/handlers/evm/index.ts:85:14)
    at async EvmHandler.isRouteApproved (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/handlers/evm/index.ts:194:20)
    at async Squid.isRouteApproved (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/index.ts:183:16)
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
```

## Acceptance Criteria

- [ ] Users of the SDK can use isRouteApproved even if a user doesn't have enough funds in their account.

**Comment by CHECKER-X** [comment]
> ## Description / Steps to reproduce
> We don't allow to check for approval using the SDK function if the user doesn't have enough funds in their account. This seems incorrect, we should return true or false, even if they don't have enough funds.
> 
> Error: Insufficient funds for account: 0x7dBd0F75aA91c757ae6564d41dd59669023D57a4 on chain 43114
>     at EvmHandler.validateTokenBalance (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/handlers/evm/utils.ts:45:13)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async EvmHandler.validateBalance (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/handlers/evm/index.ts:85:14)
>     at async EvmHandler.isRouteApproved (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/handlers/evm/index.ts:194:20)
>     at async Squid.isRouteApproved (/Users/fig/code/squid/examples/V2/sdk/swapAvalancheUsdcToMoonbeam/node_modules/@0xsquid/sdk/src/index.ts:183:16)
> Waiting for the debugger to disconnect...
> error Command failed with exit code 1.
> ## Acceptance Criteria
> * [ ]  Users of the SDK can use isRouteApproved even if a user doesn't have enough funds in their account.

[🦋🌞🍍💣💰🐝🌟🪙💡👝🍋.txt](https://github.com/user-attachments/files/19171491/default.txt)
